# Generated by Django 5.1a1 on 2024-06-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
